update and pin node version
digicatapult/vitalam-api pull request #23
Opened 2022-01-31 16:23 UTC by danielcooperxyz

2022-01-31 17:11 UTC, darrylmorton-digicatapult approved these changes

2022-01-31 17:50 UTC, n3op2 submitted a review, later dismissed

2022-02-01 09:13 UTC, dblane-digicatapult requested changes

2022-02-01 09:13 UTC, dblane-digicatapult commented on Dockerfile
Install the correct version of NPM here.  Currently this dockerfile uses whatever comes with npm.

2022-02-02 08:25 UTC, dblane-digicatapult requested changes
please pin npm version in workflows

2022-02-02 09:33 UTC, mattdean-digicatapult approved these changes

2022-02-02 09:34 UTC, mattdean-digicatapult approved these changes

2022-02-02 10:00 UTC, dblane-digicatapult approved these changes

2022-02-02 10:09 UTC, merged